# Site settings
title: Haotian LIN
description: 'Haotian LIN personal page'
url: 'http://https://haotianlin2000.github.io/'
baseurl: ''
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Haotian LIN'
  email: haotian.lin2000@gmail.com
  instagram_username: cesclin
#  facebook_username: Haotian Lin
  github_username:  haotianlin2000


# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
